# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'foram-v2-gui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Foram_GUI_proto(object):
    def setupUi(self, Foram_GUI_proto):
        Foram_GUI_proto.setObjectName("Foram_GUI_proto")
        Foram_GUI_proto.resize(800, 666)
        self.centralwidget = QtWidgets.QWidget(Foram_GUI_proto)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 500, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 20, 761, 471))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 500, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 500, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 500, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(690, 500, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(110, 540, 411, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 540, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 570, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 570, 55, 16))
        self.label_3.setObjectName("label_3")
        Foram_GUI_proto.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Foram_GUI_proto)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuPrototype = QtWidgets.QMenu(self.menubar)
        self.menuPrototype.setObjectName("menuPrototype")
        Foram_GUI_proto.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Foram_GUI_proto)
        self.statusbar.setObjectName("statusbar")
        Foram_GUI_proto.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPrototype.menuAction())

        self.retranslateUi(Foram_GUI_proto)
        QtCore.QMetaObject.connectSlotsByName(Foram_GUI_proto)

    def retranslateUi(self, Foram_GUI_proto):
        _translate = QtCore.QCoreApplication.translate
        Foram_GUI_proto.setWindowTitle(_translate("Foram_GUI_proto", "MainWindow"))
        self.pushButton.setText(_translate("Foram_GUI_proto", "Solenoid 1"))
        self.pushButton_2.setText(_translate("Foram_GUI_proto", "Solenoid 2"))
        self.pushButton_3.setText(_translate("Foram_GUI_proto", "Solenoid 3"))
        self.pushButton_4.setText(_translate("Foram_GUI_proto", "Solenoid 4"))
        self.pushButton_5.setText(_translate("Foram_GUI_proto", "Save"))
        self.label.setText(_translate("Foram_GUI_proto", "Exposure"))
        self.label_2.setText(_translate("Foram_GUI_proto", "Detected"))
        self.label_3.setText(_translate("Foram_GUI_proto", "Yes"))
        self.menuPrototype.setTitle(_translate("Foram_GUI_proto", "Prototype"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Foram_GUI_proto = QtWidgets.QMainWindow()
    ui = Ui_Foram_GUI_proto()
    ui.setupUi(Foram_GUI_proto)
    Foram_GUI_proto.show()
    sys.exit(app.exec_())
